### ISSUE TITLE
Blender4.1.1无法使用McBlender/Blender 4.1.1 does not work with McBlender

### ISSUE THREAD

**Issue by yandujun363** [Nusiq/mcblend#118]
错误日志,插件版本11.0.2/Error log, plugin version 11.0.2
```
Traceback (most recent call last):
  File "D:\mmd\blender-4.1.1-windows-x64\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mmd\blender-4.1.1-windows-x64\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\yangd\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mcblend\__init__.py", line 11, in <module>
    from .operator import (
  File "C:\Users\yangd\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mcblend\operator.py", line 21, in <module>
    from .operator_func.typed_bpy_access import (
ImportError: cannot import name 'get_mcblend_project' from 'mcblend.operator_func.typed_bpy_access' (C:\Users\yangd\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mcblend\operator_func\typed_bpy_access.py)
```

**Comment by Nusiq** [comment]
I'm not trying to support every Blender version. Mcblend 11.0.2 works with Blender 4.2.

I always try to support the newest LTS version. In the documentation, on the installation page the matching verison is always mentioned. For example, here is the installation page for Mcblend 11.0.2: https://mcblend.readthedocs.io/en/v11.0.2/installation_and_updating/. It says that you should have Blender 4.2.

Once the new Blender LTS is released, I'll update Mcblend to support it.
